language: python
python:
  - 2.7
compiler:
  - gcc
before_install:
  - sudo apt-get update
install:
  - sudo apt-get install python-dev python-numpy
before_script:
  - git clone https://github.com/Itseez/opencv.git
  - cd opencv
  - git checkout 2.4
  - mkdir build
  - cd build
  - cmake ..
  - make -j8
  - sudo make install
  - cd ../..
  - export PYTHONPATH=$PYTHONPATH:/usr/lib/python2.7/site-packages/
script:
  - pytest
